
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Sep 23 2025 16:20:49 -03 (Sep 23 2025 19:20:49 UTC)

// Verification Directory fv/multiplexor 

module multiplexor(in0, in1, sel, mux_out);
  input [4:0] in0, in1;
  input sel;
  output [4:0] mux_out;
  wire [4:0] in0, in1;
  wire sel;
  wire [4:0] mux_out;
  CLKMX2X6 g136__2398(.A (in0[4]), .B (in1[4]), .S0 (sel), .Y
       (mux_out[4]));
  CLKMX2X6 g140__5107(.A (in0[2]), .B (in1[2]), .S0 (sel), .Y
       (mux_out[2]));
  CLKMX2X6 g137__6260(.A (in0[1]), .B (in1[1]), .S0 (sel), .Y
       (mux_out[1]));
  CLKMX2X6 g138__4319(.A (in0[0]), .B (in1[0]), .S0 (sel), .Y
       (mux_out[0]));
  CLKMX2X6 g139__8428(.A (in0[3]), .B (in1[3]), .S0 (sel), .Y
       (mux_out[3]));
endmodule

